name: Build Status

on:
  push:
    # Run tests on any push to feature branches.
    branches: [ "master", "main", "DS-[0-9]+*", "ubid-test" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    name: mvn package
    runs-on: ubuntu-latest

    # Compile and build with supported LTS releases of Java.
    strategy:
      matrix:
        java-version: [ 17, 21, 25 ]
      # Run tests with each Java version sequentially.
      max-parallel: 1
    steps:
    - run: |
        echo "This job was triggered by the '${{ github.event_name }}' event."
    - uses: actions/checkout@v4
    - name: Install JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Build
      run: |
        ./mvnw clean package
